import type {IDataModel} from "./testDataModel";

export const testData: IDataModel[] = [
    {
        id: 1,
        name: 'Pont du gard',
        imageUrl: "/src/assets/pont-du-gard.jpg",
        country: "Italy",
        location: 'Rome',
        startBuilding: "1357",
        endBuilding: "1402",
    },
    {
        id: 2,
        name: 'Sarkofag Janiusza bassusa z IV w',
        imageUrl: "/src/assets/sarkofag-janiusza.jpg",
        country: "Italy",
        location: 'Rome',
        startBuilding: "",
        endBuilding: "",
    },
    {
        id: 3,
        name: 'SSanta Constanza',
        imageUrl: "/src/assets/santa-constanza.jpg",
        country: "Italy",
        location: 'Rome',
        startBuilding: "",
        endBuilding: "",
    },
    {
        id: 4,
        name: 'Hagia Sofia',
        imageUrl: "/src/assets/hagia-sofia.jpg",
        country: "Turcja",
        location: 'Stambul',
        startBuilding: "",
        endBuilding: "",
    },
    {
        id: 5,
        name: 'President Palace',
        imageUrl: "/src/assets/president-palace.jpg",
        country: "Czechy",
        location: 'Praga',
        startBuilding: "",
        endBuilding: "",
    },
    {
        id: 6,
        name: 'Siena Katedra',
        imageUrl: "/src/assets/siena-katedra.jpg",
        country: "Wlochy",
        location: 'Siena',
        startBuilding: "",
        endBuilding: "",
    },
    {
        id: 7,
        name: 'Palazzo Vecchio',
        imageUrl: "/src/assets/palazzo-vecchio.jpg",
        country: "Wlochy",
        location: 'Florencja',
        startBuilding: "",
        endBuilding: "",
    }, {
        id: 8,
        name: 'Bazylika Mariacka',
        imageUrl: "/src/assets/bazylika-mariacka.jpg",
        country: "Polska",
        location: 'Gdansk',
        startBuilding: "",
        endBuilding: "1502",
    },
    {
        id: 9,
        name: 'Oltarz Mariacki',
        imageUrl: "/src/assets/oltarz-mariany.png",
        country: "Polska",
        location: 'Krakow',
        startBuilding: "1477",
        endBuilding: "1489",
    },
    {
        id: 11,
        name: 'Nagrobek Kazimierza Wielkiego,katedra wawelska',
        imageUrl: "/src/assets/nadgrobek.png",
        country: "Poland",
        location: 'Krakow',
        startBuilding: "1370",
        endBuilding: "1380",
    },
    {
        id: 12,
        name: 'Pieta z Tubadzina',
        imageUrl: "/src/assets/nadgrobek.png",
        country: "Poland",
        location: 'muzeum narodowy w Warzawie',
        startBuilding: "ok 1450",
        endBuilding: "",
    },
    {
        id: 13,
        name: 'Barbakan',
        imageUrl: "/src/assets/barbakan.png",
        country: "Poland",
        location: 'Krakow',
        startBuilding: "koniec XV",
        endBuilding: "",
    },
    {
        id: 14,
        name: 'Kaplica palacowa w Akwizagranie',
        imageUrl: "/src/assets/kaplica.jpg",
        country: "Niemcy",
        location: 'Akwizagran',
        startBuilding: "786",
        endBuilding: "800",
    },
    {
        id: 15,
        name: 'Katedra Notre Dame',
        imageUrl: "/src/assets/notre-dam.png",
        country: "Francja",
        location: 'Paris',
        startBuilding: "1163",
        endBuilding: "",
    },
    {
        id: 16,
        name: 'Drzwi Plockie',
        imageUrl: "/src/assets/drzwi.jpeg",
        country: "Rosja",
        location: 'Novgorod',
        startBuilding: "1152",
        endBuilding: "1154",
    },
    {
        id: 17,
        name: 'Kosciol Mariacki',
        imageUrl: "/src/assets/kosciol-mariacki-w-krakowie.jpeg",
        country: "Polska",
        location: 'Krakow',
        startBuilding: "1221",
        endBuilding: "1222",
    },
    {
        id: 18,
        name: 'Brazowa statuetka Karola Wielkiego',
        imageUrl: "/src/assets/statuetka-krola.jpeg",
        country: "Najważniejsze dokonania Karola Wielkiego:\n" +
            "poprowadzenie zwycięskich wojen m.in. z Longobardami,\n" +
            "powiększenie terytorium Królestwa Franków,\n" +
            "koronacja na cesarza (odnowienie cesarstwa na Zachodzie),\n" +
            "ujednolicenie administracji m.in. ...\n" +
            "rozwój kultury i nauki (renesans karoliński).",
        location: '',
        startBuilding: "742",
        endBuilding: "814",
    },
    {
        id: 19,
        name: 'Ksiega z Durrow',
        imageUrl: "/src/assets/ksiega.jpeg",
        country: "zawierający łaciński przekład czterech Ewangelii. Stanowi najstarszy znany rękopiśmienny ewangeliarz z terenu Wysp Brytyjskich.",
        location: '',
        startBuilding: "II polowa VII wieku",
        endBuilding: "",
    },
    {
        id: 20,
        name: 'Tkanina z Bayeux',
        imageUrl: "/src/assets/tkanina-z-bayeux.jpeg",
        country: "ręcznie haftowane płótno przedstawiające podbój Anglii przez Wilhelma I Zdobywcę i bitwę pod Hastings w 1066 roku; dzieło sztuki świeckiej",
        location: 'Bayeux',
        startBuilding: "1066",
        endBuilding: "",
    },
    {
        id: 21,
        name: 'Pocalunek Iudy-Giotoo di Bondone ДЖОТТО ',
        imageUrl: "/src/assets/pocalunek.jpeg",
        country: "Italy",
        location: 'Florencja',
        startBuilding: "1303",
        endBuilding: "1305",
    },
    {
        id: 22,
        name: 'katedra w Wells',
        imageUrl: "/src/assets/katedra-w-wells.png",
        country: "Austria",
        location: 'Wells',
        startBuilding: "XII",
        endBuilding: "XIV",
    },
];

